import turtle
x=turtle.Turtle()
x.speed(999999)
turtle.bgcolor(0,0,0)
x.width(2)

from star import*
x.color("red")
star(x,5)
x.color("orange")
star(x,10)
x.color("yellow")
star(x,15)
x.color("green")
star(x,20)
x.color("blue")        
star(x,25)
x.color("purple")
star(x,30)
x.color("red")
star(x,35)
x.color("orange")
star(x,40)
x.color("yellow")
star(x,45)
x.color("green")
star(x,50)
x.color("blue")
star(x,55)
x.color("purple")
star(x,60)
x.color("red")
star(x,65)
x.color("orange")
star(x,70)
x.color("yellow")
star(x,75)
x.color("green")
star(x,80)
x.color("blue")
star(x,85)
x.color("purple")
star(x,90)
x.color("red")
star(x,95)
x.color("orange")
star(x,100)
x.color("yellow")
star(x,105)
x.color("green")
star(x,110)
x.color("blue")
star(x,115)
x.color("purple")
star(x,120)
x.color("red")
star(x,125)
x.color("orange")
star(x,130)
x.color("yellow")
star(x,135)
x.color("green")
star(x,140)
x.color("blue")
star(x,145)
x.color("purple")
star(x,150)
x.color("red")
star(x,155)
x.color("orange")
star(x,160)
x.color("yellow")
star(x,165)
x.color("green")
star(x,170)
x.color("blue")       
star(x,175)
x.color("purple")
star(x,180)
x.color("red")
star(x,185)
x.color("orange")
star(x,190)
x.color("yellow")
star(x,195)
x.color("green")
star(x,200)
#PERFECT LEAVE IT

for times in range(1):
    x.penup()
    x.goto(-336,255)
    x.pendown()
    x.color("cyan")
    x.begin_fill()
    star(x,40)
    x.end_fill()
    
for times in range(1):
    x.penup()
    x.goto(336,-255)
    x.pendown()
    x.color("violet")
    x.begin_fill()
    star(x,20)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(-332,245)
    x.pendown()
    x.color("blue")
    x.begin_fill()
    star(x,10)
    x.end_fill()
    
for times in range(1):
    x.penup()
    x.goto(332,-245)
    x.pendown()
    x.color("red")
    x.begin_fill()
    star(x,15)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(-355,130)
    x.pendown()
    x.color("pink")
    x.begin_fill()
    star(x,20)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(355,-130)
    x.pendown()
    x.color("yellow")
    x.begin_fill()
    star(x,20)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(-378,178)
    x.pendown()
    x.color("gold")
    x.begin_fill()
    star(x,20)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(378,-178)
    x.pendown()
    x.color("silver")
    x.begin_fill()
    star(x,20)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(-333,178)
    x.pendown()
    x.color("white")
    x.begin_fill()
    star(x,20)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(333,-188)
    x.pendown()
    x.color("magenta")
    x.begin_fill()
    star(x,20)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(325,72)
    x.pendown()
    x.color("purple")
    x.begin_fill()
    star(x,25)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(335,88)
    x.pendown()
    x.color("red")
    x.begin_fill()
    star(x,25)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(88,225)
    x.pendown()
    x.color("grey")
    x.begin_fill()
    star(x,25)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(88,325)
    x.pendown()
    x.color("blue")
    x.begin_fill()
    star(x,25)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(155,325)
    x.pendown()
    x.color("violet")
    x.begin_fill()
    star(x,25)
    x.end_fill()

for times in range(1):
    x.penup()
    x.goto(120,335)
    x.pendown()
    x.color("lavender")
    x.begin_fill()
    star(x,25)
    x.end_fill()
#PERFECT LEAVE IT

